import * as THREE from 'three';
import {sunInfo} from './object-info.js';
import {installPicking} from './picking.js';
import {initSound} from './sound.js';
initSound();
import { OrbitControls } from './assets/OrbitControls.js';
import { planets, elements, position } from './ephemeris.js';
import { createExtensions } from './extensions.js';
const $=id=>document.getElementById(id);
const data=[
['Mercury','mercury',.39,'約88日','クレーターに覆われた、太陽に最も近い惑星。',.03],
['Venus','venus_surface',.64,'約225日','厚い雲に覆われた惑星。ここでは雲の下の地表を表示。',177.4],
['Earth','earth_daymap',.67,'約365日','海と雲に覆われた、私たちの惑星。',23.44],
['Mars','mars',.51,'約687日','赤い大地と極冠を持つ、地球の外側の隣人。',25.2],
['Jupiter','jupiter',1.8,'約11.9年','縞模様の雲が流れる、太陽系最大の惑星。',3.1],
['Saturn','saturn',1.5,'約29.5年','氷の粒からなる広大な環を持つガス惑星。',26.7],
['Uranus','uranus',1.06,'約84年','横倒しに近い自転軸を持つ、淡い青緑の惑星。',97.8],
['Neptune','neptune',1.04,'約165年','太陽から最も遠い、青い巨大氷惑星。',28.3]
];
const root=$('universe'), host=$('viewport'), labelRoot=$('labels');
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch(e){$('loading').hidden=true;$('error').hidden=false;$('error').textContent='3D表示を開始できませんでした。WebGLに対応したSafariやChromeで開き直してください。';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x05080e);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','ドラッグで回転、ピンチまたはホイールで拡大する太陽系');
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(45,1,.025,1800),controls=new OrbitControls(camera,renderer.domElement);
controls.enableDamping=true;controls.dampingFactor=.08;controls.enablePan=false;controls.minDistance=3;controls.maxDistance=1200;controls.maxPolarAngle=Math.PI*.95;
const ambient=new THREE.AmbientLight(0x8098ba,.28);scene.add(ambient);const sunlight=new THREE.PointLight(0xfff3df,3.2,0,0);scene.add(sunlight);
const manager=new THREE.LoadingManager();let assetsFailed=false;manager.onLoad=()=>{$('loading').hidden=true;if(assetsFailed){$('error').hidden=false;$('error').textContent='一部の表面画像を読み込めませんでした。再読み込みしてください。';}};manager.onError=()=>{assetsFailed=true;$('loading').textContent='一部の表面画像を読み込めませんでした。再読み込みしてください。';};
const loader=new THREE.TextureLoader(manager);function texture(name){let t=loader.load('./assets/2k_'+name+'.jpg');t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());return t;}
const sphere=new THREE.SphereGeometry(1,64,40);
const sun=new THREE.Mesh(sphere,new THREE.MeshBasicMaterial({map:texture('sun'),color:0xffdeb0}));sun.scale.setScalar(2.55);scene.add(sun);
const glow=new THREE.Mesh(new THREE.SphereGeometry(3.6,40,24),new THREE.ShaderMaterial({uniforms:{},vertexShader:'varying vec3 n; varying vec3 v; void main(){vec4 p=modelViewMatrix*vec4(position,1.0); n=normalize(normalMatrix*normal);v=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',fragmentShader:'varying vec3 n; varying vec3 v; void main(){float f=pow(max(0.0,dot(normalize(n),normalize(v))),3.0);gl_FragColor=vec4(1.0,0.36,0.06,f*0.17);}',transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));scene.add(glow);
let bodies=[],labels=[],orbitLines=[];const orbitGroup=new THREE.Group();scene.add(orbitGroup);
planets.forEach((p,i)=>{const d=data[i],group=new THREE.Group(),tilt=new THREE.Group();tilt.rotation.z=THREE.MathUtils.degToRad(d[5]);group.add(tilt);const mesh=new THREE.Mesh(sphere,new THREE.MeshStandardMaterial({map:texture(d[1]),roughness:i===2?.72:1,metalness:0}));mesh.scale.setScalar(d[2]);tilt.add(mesh);scene.add(group);bodies.push({group,mesh,tilt});
 if(i===5){let geo=new THREE.RingGeometry(d[2]*1.25,d[2]*2.3,160);let pos=geo.attributes.position,uv=geo.attributes.uv;for(let j=0;j<pos.count;j++){let r=Math.hypot(pos.getX(j),pos.getY(j));uv.setXY(j,(r-d[2]*1.25)/(d[2]*1.05),.5)}const t=loader.load('./assets/2k_saturn_ring_alpha.png');t.colorSpace=THREE.SRGBColorSpace;const ring=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({map:t,transparent:true,side:THREE.DoubleSide,roughness:1,opacity:.92,depthWrite:false}));ring.rotation.x=-Math.PI/2;tilt.add(ring);}
 const label=document.createElement('span');label.className='planet-label';label.textContent=p[0];labelRoot.appendChild(label);labels.push(label);
 const button=document.createElement('button');button.type='button';button.setAttribute('aria-pressed',i===2);button.innerHTML=`<img src="./assets/2k_${d[1]}.jpg" alt=""><span>${p[0]}</span><small>${d[0].toUpperCase()}</small>`;button.onclick=()=>{select(i);focus();};$('planet-nav').appendChild(button);
});
const sunLabel=document.createElement('span');sunLabel.className='planet-label';sunLabel.textContent='太陽';labelRoot.appendChild(sunLabel);
let ms=Date.now(),playing=true,selected=2,focusMode=false,actual=false,raw=[],lastTime=performance.now(),lastUI=0,lastOrbit=0,flight=null,followPoint=new THREE.Vector3();
let extras=null,externalTarget=null;
const minDate=Date.UTC(1800,0,1),maxDate=Date.UTC(2050,0,1)-60000;
function map(v){const r=Math.hypot(...v);if(r<1e-12)return new THREE.Vector3();const d=actual?r*1.55:Math.log1p(r*2.7)*10.3;return new THREE.Vector3(v[0]/r*d,v[2]/r*d,-v[1]/r*d);}
function updatePositions(){raw=planets.map((p,i)=>extras?.mode==='lab'?extras.planetPosition(i):position(elements(p,ms)));bodies.forEach((b,i)=>{b.group.position.copy(map(raw[i]));b.group.visible=!extras?.isSky()&&(extras?.hasPlanet(i)??true)});const sp=extras?.mode==='lab'?map(extras.sunPosition()):new THREE.Vector3();sun.position.copy(sp);glow.position.copy(sp);sunlight.position.copy(sp);orbitGroup.visible=!extras?.isSky()&&extras?.mode!=='lab'&&$('orbits').checked;}
function orbits(){orbitLines.forEach(l=>{orbitGroup.remove(l);l.geometry.dispose();l.material.dispose()});orbitLines=[];planets.forEach((p,i)=>{let e=elements(p,ms),pts=[];for(let k=0;k<=240;k++)pts.push(map(position(e,k*Math.PI*2/240)));let line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:i===selected?0x806446:0x485364,transparent:true,opacity:i===selected?.65:.32}));orbitGroup.add(line);orbitLines.push(line)});}
function moveTo(target,offset){flight={start:performance.now(),fromTarget:controls.target.clone(),fromCamera:camera.position.clone(),target:target.clone(),offset:offset.clone()};followPoint.copy(target);}
function overview(top=false){externalTarget=null;focusMode=false;$('focus').textContent='この惑星に近づく ↗';$('overview').classList.toggle('active',!top);$('top').classList.toggle('active',top);const distance=(actual?360:150)/Math.min(1,camera.aspect*.85);moveTo(new THREE.Vector3(),top?new THREE.Vector3(0,distance,.01):new THREE.Vector3(0,distance*.49,distance*.87));}
function focus(){externalTarget=null;focusMode=true;$('focus').textContent='太陽系全体に戻る ↗';$('overview').classList.remove('active');$('top').classList.remove('active');const p=bodies[selected].group.position;const r=data[selected][2]*(selected===5?2.2:1)*(actual?.15:1);let toward=p.clone().negate().normalize(),side=new THREE.Vector3().crossVectors(toward,new THREE.Vector3(0,1,0)).normalize();let offset=toward.multiplyScalar(r*4.5).add(side.multiplyScalar(r*4.3)).add(new THREE.Vector3(0,r*2.5,0));controls.minDistance=r*2.5;moveTo(p,offset);}
function select(i){selected=i;$('name').textContent=planets[i][0];$('english').textContent=data[i][0].toUpperCase();$('number').textContent=String(i+1).padStart(2,'0')+' / 08';$('description').textContent=data[i][4];$('period').textContent=data[i][3];[...$('planet-nav').children].forEach((b,k)=>b.setAttribute('aria-pressed',k===i));labels.forEach((l,k)=>l.classList.toggle('selected',k===i));orbits();updateUI();if(focusMode)focus();}
function localValue(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
let clockLocale='',clockFormat;function getClockFormat(){const locale=document.documentElement.lang==='en'?'en-US':'ja-JP';if(locale!==clockLocale){clockLocale=locale;clockFormat=new Intl.DateTimeFormat(locale,{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',timeZoneName:'short'});}return clockFormat;}
function updateUI(){const d=new Date(ms);$('clock').textContent=getClockFormat().format(d);$('clock').dateTime=d.toISOString();if(document.activeElement!==$('date'))$('date').value=localValue(d);$('distance').textContent=raw.length?Math.hypot(...raw[selected]).toFixed(3):'—';const live=playing&&$('speed').value==='live';$('status').textContent=live?'LIVE':playing?'TIME TRAVEL':'PAUSED';$('live-dot').style.background=live?'#b4d7be':'#d4aa72';$('play').textContent=playing?'Ⅱ':'▶';$('play').setAttribute('aria-label',playing?'一時停止':'再生');}
$('focus').onclick=()=>{if(focusMode){controls.minDistance=3;overview()}else focus()};$('overview').onclick=()=>{if(extras?.isSky()){extras.home();return}controls.minDistance=3;overview()};$('top').onclick=()=>{if(extras?.isSky()){extras.home();return}controls.minDistance=3;overview(true)};
$('zoom-in').onclick=()=>{if(extras?.zoom(.78))return;flight=null;camera.position.sub(controls.target).multiplyScalar(.78).add(controls.target);controls.update()};$('zoom-out').onclick=()=>{if(extras?.zoom(1.25))return;flight=null;camera.position.sub(controls.target).multiplyScalar(1.25).add(controls.target);controls.update()};
controls.addEventListener('start',()=>{flight=null;followPoint.copy(externalTarget?externalTarget():bodies[selected].group.position)});
$('speed').onchange=()=>{playing=true;lastTime=performance.now();if($('speed').value==='live')ms=Date.now();updatePositions();updateUI()};
$('play').onclick=()=>{playing=!playing;lastTime=performance.now();if(playing&&$('speed').value==='live')ms=Date.now();updateUI()};
$('now').onclick=()=>{ms=Date.now();playing=true;$('speed').value='live';updatePositions();orbits();if(focusMode)focus();updateUI()};
$('date').onchange=()=>{let d=new Date($('date').value).getTime();if(Number.isFinite(d)){ms=Math.max(minDate,Math.min(maxDate,d));playing=false;updatePositions();orbits();if(focusMode)focus();updateUI()}};
$('orbits').onchange=()=>orbitGroup.visible=$('orbits').checked;
$('real').onchange=()=>{actual=$('real').checked;bodies.forEach(b=>b.group.scale.setScalar(actual?.15:1));sun.scale.setScalar(actual?.16:2.55);glow.scale.setScalar(actual?.063:1);$('scale-note').textContent=actual?'軌道は実際の距離比':'距離を圧縮して表示';updatePositions();orbits();extras?.redraw();if(focusMode)focus();else overview()};
$('about').onclick=()=>$('about-dialog').showModal();$('close-about').onclick=()=>$('about-dialog').close();$('about-dialog').onclick=e=>{if(e.target===$('about-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}};
function resize(){let w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.setViewOffset(w,h,-w*(w<600?.055:.09),h*.01,w,h);camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(host);resize();
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function projectLabels(){if(extras?.mode!=='solar'){labels.forEach(l=>l.hidden=true);sunLabel.hidden=true;return}let w=host.clientWidth,h=host.clientHeight,boxes=[];let order=[selected,...bodies.map((_,i)=>i).filter(i=>i!==selected)];const bound=$('detail').getBoundingClientRect(),rt=root.getBoundingClientRect(),bottom=$('planet-nav').getBoundingClientRect().top-rt.top;
 order.forEach(i=>{let b=bodies[i],l=labels[i],v=b.group.position.clone().project(camera),x=(v.x*.5+.5)*w,y=(-v.y*.5+.5)*h;l.hidden=true;if(v.z>1||v.z< -1||x<12||x>w-50||y<145||y>bottom-20)return;if(x<bound.right-rt.left+25&&y<bound.bottom-rt.top+20&&y>bound.top-rt.top-20)return;let y2=y+15;if(boxes.some(q=>Math.abs(q[0]-x)<60&&Math.abs(q[1]-y2)<22))y2+=24;if(y2>bottom-15)return;l.style.transform=`translate(${x+10}px,${y2}px)`;l.hidden=false;boxes.push([x,y2]);});let v=sun.position.clone().project(camera),x=(v.x*.5+.5)*w,y=(-v.y*.5+.5)*h;sunLabel.hidden=focusMode||v.z>1||x<0||x>w-50||y<145||y>bottom-35;sunLabel.style.transform=`translate(${x+15}px,${y+22}px)`;}
function frame(now){let dt=Math.min((now-lastTime)/1000,.2);lastTime=now;extras?.tick(dt);if(playing&&(!extras||extras.mode==='solar')){if($('speed').value==='live')ms=Date.now();else ms+=dt*1000*Number($('speed').value);if(ms>maxDate||ms<minDate){ms=Math.max(minDate,Math.min(maxDate,ms));playing=false;}}
 updatePositions();if(flight){const t=reduced?1:Math.min(1,(now-flight.start)/1100),e=1-Math.pow(1-t,3);let target=externalTarget?externalTarget():focusMode?bodies[selected].group.position:flight.target;controls.target.lerpVectors(flight.fromTarget,target,e);camera.position.lerpVectors(flight.fromCamera,target.clone().add(flight.offset),e);followPoint.copy(target);if(t===1)flight=null;}else if(focusMode||externalTarget){let next=externalTarget?externalTarget():bodies[selected].group.position,delta=next.clone().sub(followPoint);camera.position.add(delta);controls.target.add(delta);followPoint.copy(next);}
 if(!reduced&&playing){bodies.forEach((b,i)=>b.mesh.rotation.y+=dt*(i===1?-.013:.035));sun.rotation.y+=dt*.006;}
 controls.update();extras?.animateSky(dt);extras?.render(now);renderer.render(scene,camera);projectLabels();if(now-lastUI>250){if(!extras||extras.mode==='solar')updateUI();lastUI=now}if(now-lastOrbit>3000&&playing&&extras?.mode==='solar'&&$('speed').value!=='live'){orbits();extras?.redraw();lastOrbit=now}requestAnimationFrame(frame);}
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();$('error').hidden=false;$('error').textContent='3D表示が中断されました。ページを再読み込みしてください。'});
extras=createExtensions({scene,camera,controls,labelRoot,bodies,sun,glow,sunlight,host,getTime:()=>ms,map,overview,cancelFocus:()=>{flight=null;focusMode=false;externalTarget=null;},setSolarVisibility:on=>{sun.visible=on;glow.visible=on;},focusExternal:(resolver,r)=>{externalTarget=resolver;focusMode=false;controls.minDistance=r*1.3;controls.maxDistance=1200;moveTo(resolver(),new THREE.Vector3(r*4,r*3,r*5));}});
installPicking(renderer.domElement,camera,()=>extras?.isSky()?(extras.pickTargets()):[...bodies.flatMap((b,i)=>b.group.visible?[{object:b.group,activate:()=>{select(i);focus();}}]:[]),...(extras?.pickTargets()??[]),{object:sun,activate:()=>sunInfo(()=>{externalTarget=()=>sun.position;focusMode=false;controls.minDistance=4;moveTo(sun.position,new THREE.Vector3(8,6,10));})}]);
$('info-sun').onclick=()=>sunInfo(()=>{$('mode-solar').onclick();externalTarget=()=>sun.position;focusMode=false;controls.minDistance=4;moveTo(sun.position,new THREE.Vector3(8,6,10));});
updatePositions();select(2);const initialDistance=150/Math.min(1,camera.aspect*.85);camera.position.set(0,initialDistance*.49,initialDistance*.87);controls.target.set(0,0,0);controls.update();requestAnimationFrame(frame);
