import {deepObjects} from './deep-data.js';
export const kindNames={exoplanet:'太陽系外惑星',nebula:'星雲',galaxy:'銀河・銀河群',starcluster:'星団',galaxycluster:'銀河団'};
export const distanceText=o=>Number.isFinite(o.distance)?'約'+o.distance.toLocaleString()+'光年':'距離データなし';
export function createDeepView({observe,camera,host,vector,look,setMode,getMode}){
 const $=id=>document.getElementById(id),dialog=$('deep-dialog'),layer=$('deep-labels');let page=0,selected=null,markers=[];
 const normalized=s=>s.toLowerCase().replace(/[\s・-]/g,'');
 function refresh(){const query=normalized($('deep-search').value),kind=$('deep-filter').value;const list=deepObjects.filter(o=>(!kind||o.kind===kind)&&normalized(o.name+' '+(o.designation||'')+' '+(o.host||'')).includes(query));const pages=Math.max(1,Math.ceil(list.length/24));page=Math.min(page,pages-1);$('deep-count').textContent=list.length.toLocaleString()+' / '+deepObjects.length.toLocaleString();$('deep-page').textContent=(page+1)+' / '+pages;$('deep-prev').disabled=page===0;$('deep-next').disabled=page>=pages-1;const visible=list.slice(page*24,page*24+24);$('deep-grid').replaceChildren();layer.replaceChildren();markers=[];
 for(const o of visible){const v=vector(o).multiplyScalar(497),card=document.createElement('article');card.className='deep-card';const title=document.createElement('h3');title.textContent=o.name;const meta=document.createElement('p');meta.className='deep-meta';meta.textContent=kindNames[o.kind]+' · '+distanceText(o)+(o.designation?' · '+o.designation:'');const desc=document.createElement('p');desc.textContent=o.description;const actions=document.createElement('div');actions.className='deep-actions';const inspect=document.createElement('button');inspect.textContent='観察する';inspect.onclick=()=>observe(o);const go=document.createElement('button');go.textContent='方向を見る';go.onclick=()=>{dialog.close();setMode('sky');selected=o.id;look(v,25);$('deep-markers').checked=true;};const source=document.createElement('a');source.textContent='資料を見る';source.href=o.source;source.target='_blank';source.rel='noopener';actions.append(inspect,go,source);if(o.image){const img=document.createElement('img');img.src=o.image;img.alt=o.name;img.loading='lazy';img.width=600;img.height=400;img.onerror=()=>{img.hidden=true;};card.append(img);}card.append(title,meta,desc,actions);$('deep-grid').append(card);const mark=document.createElement('button');mark.className='deep-marker '+o.kind;mark.textContent=o.name;mark.hidden=true;mark.onclick=()=>observe(o);layer.append(mark);markers.push({o,v,mark});}
 }
 $('deep-search').oninput=$('deep-filter').onchange=()=>{page=0;refresh();};$('deep-prev').onclick=()=>{page--;refresh();dialog.scrollTop=0;};$('deep-next').onclick=()=>{page++;refresh();dialog.scrollTop=0;};$('open-deep').onclick=()=>{$('catalog-dialog').close();dialog.showModal();};$('sky-deep').onclick=()=>dialog.showModal();$('close-deep').onclick=()=>dialog.close();refresh();
 function render(){const w=host.clientWidth,h=host.clientHeight,clean=document.body.classList.contains('ui-hidden'),occupied=[];markers.sort((a,b)=>(b.o.id===selected?1:0)-(a.o.id===selected?1:0));for(const m of markers){m.mark.hidden=true;if(getMode()!=='sky'||!$('deep-markers').checked)continue;const q=m.v.clone().project(camera),x=(q.x+1)*w/2,y=(1-q.y)*h/2;if(q.z< -1||q.z>1||x<10||x>w-25||y<(clean?60:285)||y>h-(clean?30:145))continue;const left=Math.max(8,Math.min(w-205,x-8));if(occupied.some(p=>Math.abs(p[0]-left)<190&&Math.abs(p[1]-y)<42))continue;m.mark.style.transform=`translate(${left}px,${y}px)`;m.mark.hidden=false;occupied.push([left,y]);}}
 return {render};
}
