// Catalog snapshot: 2026-09-06. RA in hours, Dec in degrees; approximate J2000 directions.
export const deepObjects=[
  {
    "id": "proxima",
    "name": "プロキシマ・ケンタウリb",
    "kind": "exoplanet",
    "con": "ケンタウルス座",
    "ra": 14.492897713333333,
    "dec": -62.6761821,
    "distance": 4.2,
    "period": 11.18,
    "description": "地球に最も近い恒星の一つ、プロキシマ・ケンタウリを回る惑星。約11.2日で一周します。海や生命の存在は確認されていません。",
    "source": "https://science.nasa.gov/exoplanet-catalog/proxima-centauri-b/",
    "image": "./assets/proxima.jpg",
    "credit": "ESO/M. Kornmesser",
    "imageKind": "想像図",
    "imageSource": "https://www.nasa.gov/image-article/artists-view-of-planet-where-liquid-water-might-exist/"
  },
  {
    "id": "trappist",
    "name": "TRAPPIST-1e",
    "kind": "exoplanet",
    "con": "みずがめ座",
    "ra": 23.108426126666664,
    "dec": -5.0434618,
    "distance": 40.5,
    "period": 6.1,
    "description": "地球に近い大きさの惑星が7つ並ぶ系の一員。恒星から受ける光の量が地球に比較的近く、大気の研究で注目されています。",
    "source": "https://science.nasa.gov/exoplanet-catalog/trappist-1-e/",
    "image": "./assets/trappist.jpg",
    "credit": "NASA, ESA, CSA, STScI, Joseph Olmsted (STScI)",
    "imageKind": "想像図",
    "imageSource": "https://science.nasa.gov/asset/webb/trappist-1-e-artists-concept/"
  },
  {
    "id": "pegasi",
    "name": "ペガスス座51番星b",
    "kind": "exoplanet",
    "con": "ペガスス座",
    "ra": 22.957835993333333,
    "dec": 20.7690958,
    "distance": 50.4,
    "period": 4.23,
    "description": "1995年に発見された、太陽に似た恒星を回る系外惑星の先駆け。恒星のすぐ近くを約4.2日で一周する高温の巨大ガス惑星です。",
    "source": "https://science.nasa.gov/exoplanet-catalog/51-pegasi-b/",
    "image": null,
    "credit": "",
    "imageKind": "想像図"
  },
  {
    "id": "kepler",
    "name": "ケプラー186f",
    "kind": "exoplanet",
    "con": "はくちょう座",
    "ra": 19.9101824,
    "dec": 43.9549884,
    "distance": 579.2,
    "period": 129.94,
    "description": "地球に近い大きさを持ち、恒星のハビタブルゾーンを回る惑星として知られています。この領域にあるだけで生命や液体の水が保証されるわけではありません。",
    "source": "https://science.nasa.gov/exoplanet-catalog/kepler-186-f/",
    "image": "./assets/kepler.jpg",
    "credit": "NASA/Ames/SETI Institute/JPL-Caltech",
    "imageKind": "想像図",
    "imageSource": "https://science.nasa.gov/exoplanet-catalog/kepler-186-f/"
  },
  {
    "id": "orion",
    "name": "オリオン大星雲",
    "kind": "nebula",
    "con": "オリオン座",
    "ra": 5.588,
    "dec": -5.391,
    "distance": 1500,
    "designation": "M42",
    "description": "ガスと塵の中で新しい星が生まれている、代表的な星形成領域です。",
    "source": "https://science.nasa.gov/asset/hubble/orion-nebula-2/",
    "image": "./assets/orion-nebula.jpg",
    "credit": "NASA, ESA, M. Robberto (STScI/ESA) and the Hubble Space Telescope Orion Treasury Project Team",
    "imageKind": "観測画像",
    "imageSource": "https://esahubble.org/images/heic0601a/"
  },
  {
    "id": "crab",
    "name": "かに星雲",
    "kind": "nebula",
    "con": "おうし座",
    "ra": 5.5756,
    "dec": 22.0145,
    "distance": 6500,
    "designation": "M1",
    "description": "1054年に観測された超新星の残骸。中心には高速で回転する中性子星、パルサーがあります。",
    "source": "https://science.nasa.gov/mission/hubble/science/explore-the-night-sky/hubble-messier-catalog/messier-1/",
    "image": "./assets/crab-nebula.jpg",
    "credit": "NASA, ESA and Allison Loll/Jeff Hester (Arizona State University); acknowledgement: Davide De Martin (ESA/Hubble)",
    "imageKind": "観測画像",
    "imageSource": "https://esahubble.org/images/heic0515a/"
  },
  {
    "id": "ring",
    "name": "環状星雲",
    "kind": "nebula",
    "con": "こと座",
    "ra": 18.8931,
    "dec": 33.029,
    "distance": 2500,
    "designation": "M57",
    "description": "年老いた恒星が放出したガスが輝く惑星状星雲。「惑星状」という名前ですが、惑星そのものではありません。",
    "source": "https://science.nasa.gov/asset/webb/ring-nebula-nircam-image/",
    "image": "./assets/ring-nebula.jpg",
    "credit": "NASA, ESA, and C. Robert O’Dell (Vanderbilt University)",
    "imageKind": "観測画像",
    "imageSource": "https://esahubble.org/images/heic1310a/"
  },
  {
    "id": "carina",
    "name": "イータカリーナ星雲",
    "kind": "nebula",
    "con": "りゅうこつ座",
    "ra": 10.741333333333332,
    "dec": -59.596525,
    "distance": 7500,
    "designation": "NGC 3372",
    "description": "巨大な星が集まる、広大な星形成領域。恒星の強い光や風が周囲のガスと塵の形を変えています。",
    "source": "https://science.nasa.gov/mission/hubble/science/explore-the-night-sky/hubble-caldwell-catalog/caldwell-92/",
    "image": "./assets/carina-nebula.jpg",
    "credit": "NASA, ESA, N. Smith (UC Berkeley), and The Hubble Heritage Team (STScI/AURA)",
    "imageKind": "観測画像",
    "imageSource": "https://esahubble.org/images/heic0707a/"
  }
];

import {expandedObjects} from './expanded-data.js';
deepObjects.push(...expandedObjects);
