import {dwarfInfo} from './object-info.js';
import * as THREE from 'three';
import {dwarfs} from './dwarfs.js';
import {position} from './ephemeris.js';
export function dwarfElements(d,ms){const M=d.ma+(ms/86400000+2440587.5-d.epoch)*d.n;return [d.a,d.e,d.i,M+d.w+d.om,d.w+d.om,d.om]}
export function createDwarfs({scene,ctx,label,setMode,projectLabel,getMode}){
const $=id=>document.getElementById(id),group=new THREE.Group();scene.add(group);let views=[];
for(const d of dwarfs){const geometry=new THREE.SphereGeometry(d.size,40,28);const mesh=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:d.color,roughness:.9}));if(d.id==='136108')mesh.scale.set(1.5,.65,1);group.add(mesh);const orbit=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0xb9a99d,transparent:true,opacity:.3}));group.add(orbit);const v={d,mesh,orbit,l:label(d.name),visible:true};views.push(v);const row=document.createElement('div');row.className='object-row';const name=document.createElement('span');name.textContent=d.name;const small=document.createElement('small');small.textContent='準惑星 · 公転 約'+Math.round(360/d.n/365.25)+'年';name.appendChild(small);const toggle=document.createElement('button');toggle.textContent='表示中';toggle.setAttribute('aria-pressed',true);toggle.onclick=()=>{v.visible=!v.visible;toggle.textContent=v.visible?'表示中':'非表示';toggle.setAttribute('aria-pressed',v.visible)};const go=document.createElement('button');go.textContent='接近';v.activate=go.onclick=()=>{setMode('solar');v.visible=true;toggle.textContent='表示中';toggle.setAttribute('aria-pressed',true);update(false);ctx.focusExternal(()=>mesh.position,d.size*1.5);$('extra-summary').hidden=false;$('extra-summary').textContent=d.name+' ｜ '+d.description+'\n準惑星 · 位置は二体近似・表面は模式表示';$('catalog-dialog').close()};const info=document.createElement('button');info.textContent='情報';info.onclick=()=>dwarfInfo(d,v.activate);row.append(name,toggle,go,info);$('dwarf-list').appendChild(row);}
function update(redraw=false){group.visible=getMode()==='solar';for(const v of views){const e=dwarfElements(v.d,ctx.getTime());v.mesh.position.copy(ctx.map(position(e)));v.mesh.visible=v.visible;v.orbit.visible=v.visible&&$('orbits').checked;if(redraw){const pts=[];for(let k=0;k<=240;k++)pts.push(ctx.map(position(e,k*Math.PI*2/240)));v.orbit.geometry.dispose();v.orbit.geometry=new THREE.BufferGeometry().setFromPoints(pts)}}}
function render(){for(const v of views){if(group.visible&&v.visible)projectLabel(v.l,v.mesh.position,195);else v.l.hidden=true;}}
update(true);return {update,render,pickTargets:()=>views.filter(v=>v.visible).map(v=>({object:v.mesh,activate:()=>dwarfInfo(v.d,v.activate)}))};
}
