import {starInfo,cometInfo,labInfo} from './object-info.js';
import {english} from './i18n.js';
import * as THREE from 'three';
import {createDeepStage} from './deep-stage.js';
import {createDeepView} from './deep-view.js';
import {createDwarfs} from './dwarf-view.js';
import {stars,constellations,comets} from './catalog.js';
import {planets,elements,position} from './ephemeris.js';
import {G,EARTH_MASS,planetMass,integrate,cloneState} from './physics.js';
const $=id=>document.getElementById(id),rad=Math.PI/180;
export function cometElements(c,ms){const a=c.q/(1-c.e),M=(ms-c.tp)/86400000*Math.sqrt(G/a**3)/rad;return [a,c.e,c.i,M+c.w+c.node,c.w+c.node,c.node]}
export function cometPosition(c,ms){const el=cometElements(c,ms),M=((el[3]-el[4])*rad%(Math.PI*2)+Math.PI*3)%(Math.PI*2)-Math.PI;let lo=-Math.PI,hi=Math.PI;for(let k=0;k<52;k++){const m=(lo+hi)/2;if(m-el[1]*Math.sin(m)<M)lo=m;else hi=m;}return position(el,(lo+hi)/2)}
export function starVector(s){const ra=s.ra*15*rad,dec=s.dec*rad,e=23.43928*rad,x=Math.cos(dec)*Math.cos(ra),y=Math.cos(dec)*Math.sin(ra),z=Math.sin(dec);return new THREE.Vector3(x,-y*Math.sin(e)+z*Math.cos(e),-(y*Math.cos(e)+z*Math.sin(e)))}
export function createExtensions(ctx){
const {scene,camera,controls,labelRoot,bodies,sun,glow,sunlight}=ctx;
const api={mode:'solar',state:[],elapsed:0,run:false};let history=[],nextId=1,lastTrail=0,lastUI=0,activeStar=null,chosenCon=0,selectedStarIds=new Set(constellations[0][2].flat());
const sky=new THREE.Group();scene.add(sky);let starMap=new Map(),skyLabels=[];
const attributes={position:[],color:[],size:[]};
stars.forEach(s=>{const v=starVector(s).multiplyScalar(500);starMap.set(s.id,{...s,v});attributes.position.push(...v.toArray());const c=new THREE.Color(s.ci>1.1?0xffbe8c:s.ci<0?0xb7d4ff:0xf1f1e7);attributes.color.push(c.r,c.g,c.b);attributes.size.push(Math.max(1.2,5.6-s.mag*.8));if(s.named){let l=document.createElement('span');l.className='sky-label';l.textContent=s.name;labelRoot.appendChild(l);skyLabels.push({s,v,l});}});
const sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.Float32BufferAttribute(attributes.position,3));sg.setAttribute('color',new THREE.Float32BufferAttribute(attributes.color,3));sg.setAttribute('size',new THREE.Float32BufferAttribute(attributes.size,1));
const sm=new THREE.ShaderMaterial({vertexColors:true,uniforms:{pixelRatio:{value:Math.min(devicePixelRatio,2)}},vertexShader:'attribute float size; uniform float pixelRatio; varying vec3 vColor; void main(){vColor=color;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);gl_PointSize=size*pixelRatio;}',fragmentShader:'varying vec3 vColor; void main(){float r=length(gl_PointCoord-0.5)*2.0;if(r>1.0)discard;gl_FragColor=vec4(vColor,pow(1.0-r,0.55));}',transparent:true,depthWrite:false});sky.add(new THREE.Points(sg,sm));
let constellationLines=[];
constellations.forEach((g,idx)=>{let coords=[];g[2].forEach(line=>{for(let k=1;k<line.length;k++){let a=starMap.get(line[k-1]).v,b=starMap.get(line[k]).v;for(let j=0;j<12;j++)coords.push(...a.clone().lerp(b,j/12).normalize().multiplyScalar(498).toArray(),...a.clone().lerp(b,(j+1)/12).normalize().multiplyScalar(498).toArray())}});let geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(coords,3));let line=new THREE.LineSegments(geo,new THREE.LineBasicMaterial({color:0x7eafe0,transparent:true,opacity:.25}));sky.add(line);constellationLines.push(line);const o=new Option(g[1],String(idx));$('constellation-select').add(o)});
let skyFlight=null;
controls.addEventListener('start',()=>{skyFlight=null;controls.enableDamping=true;});
function skyLook(v,fov=56){
 ctx.cancelFocus();const from=camera.position.clone().sub(controls.target).normalize(),to=v.clone().normalize().negate();
 controls.target.set(0,0,0);controls.minDistance=.1;controls.maxDistance=.1;controls.enableDamping=false;
 skyFlight={elapsed:0,from,rotation:new THREE.Quaternion().setFromUnitVectors(from,to),fov:camera.fov,toFov:fov};
 camera.position.copy(from).multiplyScalar(.1);camera.lookAt(controls.target);controls.update();
}
api.animateSky=dt=>{if(!skyFlight||api.mode!=='sky')return;const f=skyFlight;f.elapsed+=dt;const t=Math.min(1,f.elapsed/1.25),ease=t*t*(3-2*t);const q=new THREE.Quaternion().slerp(f.rotation,ease);camera.position.copy(f.from).applyQuaternion(q).multiplyScalar(.1);camera.fov=THREE.MathUtils.lerp(f.fov,f.toFov,ease);camera.updateProjectionMatrix();camera.lookAt(controls.target);controls.update();if(t===1){skyFlight=null;controls.enableDamping=true;}};
function chooseConstellation(i){chosenCon=i;selectedStarIds=new Set(constellations[i][2].flat());const g=constellations[i],ids=[...new Set(g[2].flat())],v=new THREE.Vector3();ids.forEach(id=>v.add(starMap.get(id).v.clone().normalize()));v.normalize();const max=Math.max(...ids.map(id=>v.angleTo(starMap.get(id).v)));const fov=THREE.MathUtils.clamp(max/rad*2.5/Math.min(1,camera.aspect),25,105);skyLook(v,fov);constellationLines.forEach((l,k)=>l.material.opacity=k===i?.8:.07);$('extra-summary').textContent=g[1]+' ｜ 全88星座 · '+ids.length+'個の星を結ぶ線（J2000）';}
$('constellation-select').onchange=()=>chooseConstellation(+$('constellation-select').value);
const named=[...stars].sort((a,b)=>a.mag-b.mag);
function filterStars(){const query=$('star-search').value.trim().toLowerCase(),old=$('star-select').value;const matches=named.filter(s=>(s.name+' '+s.con+' '+english(s.name)+' '+english(s.con)+' HIP '+s.id).toLowerCase().includes(query));$('star-select').replaceChildren();matches.forEach(s=>$('star-select').add(new Option(s.name+' · '+s.con,String(s.id))));if(matches.some(s=>String(s.id)===old))$('star-select').value=old;$('star-count').textContent=matches.length+' / '+stars.length;$('look-star').disabled=$('info-star').disabled=!matches.length;if(matches.length)showStarInfo();else{$('star-info').textContent='該当する星がありません。';activeStar=null;}}
$('star-search').oninput=filterStars;filterStars();
function lookAtStar(s){setMode('sky');activeStar=s;skyLook(s.v,40);$('catalog-dialog').close();}
$('info-star').onclick=()=>{if(activeStar)starInfo(activeStar,()=>lookAtStar(activeStar));};
function showStarInfo(){const s=starMap.get(+$('star-select').value);if(!s)return;activeStar=s;$('star-info').textContent=`${s.name} / ${s.con}\n見かけの等級 ${s.mag} 等 · 星表の距離 約${s.dist.toLocaleString()}光年`;}showStarInfo();$('star-select').onchange=showStarInfo;
$('look-star').onclick=()=>{setMode('sky');showStarInfo();skyLook(activeStar.v,40);$('extra-summary').textContent=$('star-info').textContent;$('catalog-dialog').close();};
function label(name,klass='extra-label'){let l=document.createElement('span');l.className=klass;l.textContent=name;labelRoot.appendChild(l);return l}
const cometGroup=new THREE.Group();scene.add(cometGroup);let cometBodies=[];
comets.forEach((c,i)=>{let group=new THREE.Group(),core=new THREE.Mesh(new THREE.SphereGeometry(.17,16,12),new THREE.MeshBasicMaterial({color:0xc9f8ef}));group.add(core);const tail=new THREE.Mesh(new THREE.ConeGeometry(.65,1,24,1,true),new THREE.ShaderMaterial({vertexShader:'varying float y; void main(){y=position.y;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'varying float y; void main(){gl_FragColor=vec4(0.32,0.83,0.97,0.18*(y+0.5));}',side:THREE.DoubleSide,transparent:true,depthWrite:false}));group.add(tail);cometGroup.add(group);let line=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0x70b8b1,transparent:true,opacity:.35}));cometGroup.add(line);cometBodies.push({c,group,tail,line,l:label(c.name),visible:true});let row=document.createElement('div');row.className='object-row';let title=document.createElement('span');title.textContent=c.name;let small=document.createElement('small');small.textContent=c.id+' · 二体近似';title.appendChild(small);let toggle=document.createElement('button');toggle.textContent='表示中';toggle.setAttribute('aria-pressed','true');toggle.onclick=()=>{const b=cometBodies[i];b.visible=!b.visible;toggle.textContent=b.visible?'表示中':'非表示';toggle.setAttribute('aria-pressed',b.visible);};let view=document.createElement('button');view.textContent='接近';view.onclick=()=>{setMode('solar');cometBodies[i].visible=true;toggle.textContent='表示中';toggle.setAttribute('aria-pressed',true);ctx.focusExternal(()=>group.position,1.7);$('extra-summary').hidden=false;$('extra-summary').textContent=c.name+' ｜ 参考位置・尾は太陽と反対方向（強調表示）';$('catalog-dialog').close()};const info=document.createElement('button');info.textContent='情報';info.onclick=()=>cometInfo(c,view.onclick);cometBodies[i].activate=view.onclick;row.append(title,toggle,view,info);$('comet-list').appendChild(row);});
function updateComets(ms,redraw){cometBodies.forEach(b=>{b.group.visible=b.visible&&api.mode==='solar';b.line.visible=b.group.visible&&$('orbits').checked;if(api.mode!=='solar'){b.l.hidden=true;return}const e=cometElements(b.c,ms),v=cometPosition(b.c,ms),r=Math.hypot(...v);b.group.position.copy(ctx.map(v));const dir=b.group.position.clone().normalize();let len=THREE.MathUtils.clamp(13/(r+.8),.08,6);b.tail.scale.y=len;b.tail.position.copy(dir.clone().multiplyScalar(len/2));b.tail.quaternion.setFromUnitVectors(new THREE.Vector3(0,-1,0),dir);if(redraw){let pts=[];for(let k=0;k<=240;k++)pts.push(ctx.map(position(e,k*Math.PI*2/240)));b.line.geometry.dispose();b.line.geometry=new THREE.BufferGeometry().setFromPoints(pts)}})}
const stage=createDeepStage(ctx,()=>setMode('deep'),()=>api.mode);
const deepSystem=createDeepView({observe:stage.observe,camera,host:ctx.host,vector:starVector,look:skyLook,setMode,getMode:()=>api.mode});
const dwarfSystem=createDwarfs({scene,ctx,label,setMode,projectLabel,getMode:()=>api.mode});
const labGroup=new THREE.Group();scene.add(labGroup);let labViews=new Map();
function disposeView(v){labGroup.remove(v.group,v.trail);v.group.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){if(o.material.map)o.material.map.dispose();o.material.dispose()}});v.trail.geometry.dispose();v.trail.material.dispose();v.l.remove()}
function syncLabViews(){for(const [id,v] of labViews)if(!api.state.some(b=>b.id===id)){disposeView(v);labViews.delete(id)}api.state.forEach(b=>{if(b.id==='sun'||labViews.has(b.id))return;let group=new THREE.Group();if(b.index!==undefined){}else if(b.type==='blackhole'){group.add(new THREE.Mesh(new THREE.SphereGeometry(.5,32,24),new THREE.MeshBasicMaterial({color:0x000000})));let disk=new THREE.Mesh(new THREE.RingGeometry(.57,1.5,100,12),new THREE.ShaderMaterial({side:THREE.DoubleSide,transparent:true,depthWrite:false,vertexShader:'varying vec3 p; void main(){p=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'varying vec3 p; void main(){float r=length(p.xy);float bands=0.75+0.25*sin(r*95.0);float a=clamp((1.5-r)*1.2,0.0,0.85)*bands;vec3 c=mix(vec3(1.,0.22,0.02),vec3(1.,0.93,0.72),pow(1.0/r,2.0)*0.3);gl_FragColor=vec4(c,a);}'}));disk.rotation.x=-Math.PI*.38;group.add(disk);}else{let t=new THREE.TextureLoader().load('./assets/2k_'+b.texture+'.jpg');t.colorSpace=THREE.SRGBColorSpace;group.add(new THREE.Mesh(new THREE.SphereGeometry(.48,32,24),new THREE.MeshStandardMaterial({map:t,roughness:1})))}let trail=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:b.type==='blackhole'?0xe5a667:0x99cce4,transparent:true,opacity:.6}));labGroup.add(group,trail);labViews.set(b.id,{group,trail,l:label(b.name),points:[]})});}
function initialState(){const ms=ctx.getTime();api.state=[{id:'sun',name:'太陽',type:'sun',mass:1,p:[0,0,0],v:[0,0,0]}];planets.forEach((p,i)=>{let a=position(elements(p,ms-43200000)),b=position(elements(p,ms+43200000));api.state.push({id:'p'+i,index:i,name:p[0],type:'planet',mass:planetMass[i],p:position(elements(p,ms)),v:b.map((x,k)=>x-a[k])})});api.elapsed=0;api.run=false;history=[];syncLabViews();renderLabList();}
function checkpoint(){history.push({state:cloneState(api.state),elapsed:api.elapsed});if(history.length>15)history.shift();$('undo-lab').disabled=false;}
function renderLabList(){syncLabViews();$('lab-list').replaceChildren();api.state.forEach(b=>{let row=document.createElement('div');row.className='object-row';let name=document.createElement('span');name.textContent=b.name;const small=document.createElement('small');small.textContent=b.type==='blackhole'?b.mass.toFixed(1)+' 太陽質量':b.id==='sun'?'1 太陽質量':(b.mass/EARTH_MASS).toFixed(1)+' 地球質量';name.appendChild(small);let view=document.createElement('button');view.textContent='接近';view.onclick=()=>{ctx.focusExternal(()=>ctx.map(api.state.find(x=>x.id===b.id)?.p??[0,0,0]),b.type==='blackhole'?1.5:.8);$('lab-dialog').close()};const info=document.createElement('button');info.textContent='情報';info.onclick=()=>labInfo(b,view.onclick);row.append(name,view,info);if(b.id!=='sun'){let del=document.createElement('button');del.textContent='削除';del.className='delete-body';del.onclick=()=>{checkpoint();api.state=api.state.filter(x=>x.id!==b.id);ctx.cancelFocus();renderLabList();$('lab-message').textContent=b.name+'を削除しました。'};row.append(del)}$('lab-list').appendChild(row)});$('undo-lab').disabled=!history.length;}
$('undo-lab').onclick=()=>{const h=history.pop();if(!h)return;api.state=cloneState(h.state);api.elapsed=h.elapsed;api.run=false;ctx.cancelFocus();labViews.forEach(v=>v.points=[]);renderLabList();};
$('reset-lab').onclick=()=>{initialState();ctx.cancelFocus();ctx.overview();$('extra-summary').textContent='初期の太陽系に戻しました。';};
$('body-type').onchange=()=>{const bh=$('body-type').value==='blackhole';$('mass-label').firstChild.textContent=bh?'質量（太陽 = 1）':'質量（地球 = 1）';$('body-mass').min=bh?'1':'0.1';$('body-mass').max=bh?'30':'1000';$('body-mass').value=bh?'5':'1';$('body-velocity').value=bh?'0':'1';$('texture-label').hidden=bh;$('body-name').placeholder=bh?'ブラックホール':'新しい惑星';};
$('add-body').onsubmit=e=>{e.preventDefault();if(!$('add-body').reportValidity())return;if(api.state.length>=24){$('lab-message').textContent='最大24天体です。先に天体を削除してください。';return}const radius=+$('body-radius').value,angle=+$('body-angle').value*rad,mass=+$('body-mass').value,bh=$('body-type').value==='blackhole';if(![radius,angle,mass].every(Number.isFinite))return;checkpoint();let speed=Math.sqrt(G/radius)*+$('body-velocity').value;const name=$('body-name').value.trim()||(bh?'ブラックホール ':'惑星 ')+nextId;api.state.push({id:'custom'+nextId++,name,type:bh?'blackhole':'planet',texture:$('body-texture').value,mass:mass*(bh?1:EARTH_MASS),p:[radius*Math.cos(angle),radius*Math.sin(angle),0],v:[-speed*Math.sin(angle),speed*Math.cos(angle),0]});renderLabList();$('lab-message').textContent=name+'を追加しました。閉じて「実験を再生」で重力の変化を見られます。';$('body-name').value='';};
$('lab-play').onclick=()=>{api.run=!api.run};
function setMode(mode){const previous=api.mode;skyFlight=null;controls.enableDamping=true;api.mode=mode;document.body.dataset.mode=mode;for(const m of ['solar','sky','lab'])$('mode-'+m).setAttribute('aria-pressed',m===mode);$('sky-tools').hidden=mode!=='sky';$('lab-tools').hidden=mode!=='lab';$('lab-timeline').hidden=mode!=='lab';$('extra-summary').hidden=mode==='solar';ctx.cancelFocus();camera.fov=45;camera.updateProjectionMatrix();controls.minDistance=3;controls.maxDistance=1200;sky.visible=true;labGroup.visible=mode==='lab';if(mode!=='lab')api.run=false;if(mode==='lab'){if(!api.state.length)initialState();$('extra-summary').textContent='自由実験 ｜ ニュートン重力・天体サイズは強調表示';ctx.overview();if(previous!==mode)$('lab-dialog').showModal();}else if(mode==='deep'){sky.visible=false;$('extra-summary').hidden=true;}else if(mode==='sky'){chooseConstellation(chosenCon);}else{ctx.overview();}ctx.setSolarVisibility(mode!=='sky'&&mode!=='deep');$('scale-note').textContent=mode==='sky'?'恒星は天球へ投影':mode==='lab'?'自由実験・軌道は計算結果':$('real').checked?'軌道は実際の距離比':'距離を圧縮して表示';}
for(const mode of ['solar','sky','lab'])$('mode-'+mode).onclick=()=>setMode(mode);
$('open-catalog').onclick=()=>$('catalog-dialog').showModal();$('close-catalog').onclick=()=>$('catalog-dialog').close();$('open-lab').onclick=()=>{$('lab-dialog').showModal();renderLabList()};$('close-lab').onclick=()=>$('lab-dialog').close();
function projectLabel(l,v,minY=190){const q=v.clone().project(camera),w=ctx.host.clientWidth,h=ctx.host.clientHeight,x=(q.x*.5+.5)*w,y=(-q.y*.5+.5)*h;l.hidden=q.z>1||q.z< -1||x<5||x>w-145||y<minY||y>h-160;if(!l.hidden)l.style.transform=`translate(${x+8}px,${y+8}px)`;return {x,y};}
// Separate label collision handling keeps the bright-star map legible on a phone.
api.render=(now)=>{dwarfSystem.render();deepSystem.render();stage.render();let used=[];skyLabels.forEach(({s,v,l})=>{l.hidden=true;if(api.mode!=='sky'||!$('star-names').checked||(!selectedStarIds.has(s.id)&&s.id!==activeStar?.id))return;const q=v.clone().project(camera),w=ctx.host.clientWidth,h=ctx.host.clientHeight,x=(q.x*.5+.5)*w,y=(-q.y*.5+.5)*h;if(q.z>1||q.z< -1||x<8||x>w-145||y<270||y>h-125||used.some(p=>Math.abs(p[0]-x)<135&&Math.abs(p[1]-y)<26))return;l.hidden=false;l.style.transform=`translate(${x+8}px,${y}px)`;used.push([x,y])});cometBodies.forEach(b=>{if(api.mode==='solar'&&b.visible)projectLabel(b.l,b.group.position,195);else b.l.hidden=true});for(const [id,v]of labViews){const b=api.state.find(b=>b.id===id);v.group.visible=api.mode==='lab'&&!!b;v.trail.visible=v.group.visible&&$('orbits').checked;if(v.group.visible){v.group.position.copy(ctx.map(b.p));projectLabel(v.l,v.group.position,270);if(now-lastTrail>120&&api.run){v.points.push(v.group.position.clone());if(v.points.length>160)v.points.shift();v.trail.geometry.dispose();v.trail.geometry=new THREE.BufferGeometry().setFromPoints(v.points)}}else v.l.hidden=true;}if(now-lastTrail>120)lastTrail=now;if(now-lastUI>200){if(api.mode==='lab'){$('status').textContent='SANDBOX';$('clock').textContent='自由実験 · '+api.state.length+'天体';$('lab-elapsed').textContent='経過 '+api.elapsed.toFixed(1)+'日';$('lab-play').textContent=api.run?'Ⅱ 一時停止':'▶ 実験を再生';}else if(api.mode==='sky'){$('status').textContent='STAR ATLAS';$('clock').textContent='HYG星表 · J2000座標';}lastUI=now;}};
api.tick=dt=>{if(api.mode==='lab'&&api.run){const done=integrate(api.state,dt*+$('lab-speed').value);api.elapsed+=done;}updateComets(ctx.getTime(),false);dwarfSystem.update(false);};
api.redraw=()=>{updateComets(ctx.getTime(),true);dwarfSystem.update(true)};
api.planetPosition=i=>api.state.find(b=>b.index===i)?.p??[0,0,0];api.hasPlanet=i=>api.mode!=='lab'||api.state.some(b=>b.index===i);api.sunPosition=()=>api.state.find(b=>b.id==='sun')?.p??[0,0,0];api.isSky=()=>api.mode==='sky'||api.mode==='deep';api.home=()=>api.mode==='deep'?stage.home():chooseConstellation(chosenCon);api.zoom=sign=>{if(api.mode!=='sky')return false;skyFlight=null;controls.enableDamping=true;camera.fov=THREE.MathUtils.clamp(camera.fov*sign,15,110);camera.updateProjectionMatrix();return true};
api.pickTargets=()=>api.mode==='deep'?stage.targets():api.mode==='sky'?[...starMap.values()].map(s=>({position:s.v,activate:()=>starInfo(s,()=>lookAtStar(s))})):api.mode==='solar'?[...dwarfSystem.pickTargets(),...cometBodies.filter(b=>b.visible).map(b=>({object:b.group,activate:()=>cometInfo(b.c,b.activate)}))]:api.mode==='lab'?[...labViews].filter(([id,v])=>v.group.visible&&v.group.children.length).map(([id,v])=>({object:v.group,activate:()=>labInfo(api.state.find(b=>b.id===id),()=>ctx.focusExternal(()=>v.group.position,.8))})):[];
updateComets(ctx.getTime(),true);document.body.dataset.mode='solar';return api;
}
