// Original synthesized ambient score and interface sounds. No recorded music.
export function initSound(){
const $=id=>document.getElementById(id);let ctx=null,master,music,effects,timer=null,on=true,step=0,next=0;const voices=new Set();
const chords=[[48,55,62,64],[45,52,59,62],[41,48,55,60],[43,50,57,62]];
function stopVoices(kind){for(const v of [...voices])if(!kind||v.kind===kind){try{v.osc.stop()}catch{}v.osc.disconnect();v.amp.disconnect();voices.delete(v)}}
function note(midi,when,duration,volume,kind,type='sine'){if(!ctx||voices.size>56)return;const osc=ctx.createOscillator(),amp=ctx.createGain();osc.type=type;osc.frequency.value=440*Math.pow(2,(midi-69)/12);const attack=kind==='music'?1.2:.015;const t=ctx.currentTime+when;amp.gain.setValueAtTime(0,t);amp.gain.linearRampToValueAtTime(volume,t+Math.min(attack,duration*.2));amp.gain.exponentialRampToValueAtTime(.0001,t+duration);osc.connect(amp);amp.connect(kind==='music'?music:effects);const v={osc,amp,kind};voices.add(v);osc.onended=()=>{osc.disconnect();amp.disconnect();voices.delete(v)};osc.start(t);osc.stop(t+duration+.05);}
function schedule(){if(!on||!$('music-enabled').checked||document.hidden||ctx?.state!=='running')return;while(next<ctx.currentTime+.7){const chord=chords[step%chords.length],offset=Math.max(0,next-ctx.currentTime);chord.forEach((n,i)=>note(n,offset+i*.05,7,.052,'music'));note(chord[2]+12,offset+1.3,3.8,.035,'music');note(chord[3]+12,offset+3.6,3,.026,'music');step++;next+=6;}}
function update(){if(ctx){const t=ctx.currentTime;master.gain.setTargetAtTime(on?+$('master-volume').value/100*.45:0,t,.07);music.gain.setTargetAtTime($('music-enabled').checked?1:0,t,.2);effects.gain.setTargetAtTime($('effects-enabled').checked?1:0,t,.03);}$('volume-value').textContent=$('master-volume').value+'%';$('sound-toggle').textContent=on?(ctx?.state==='running'?'♪ 音声オン':'♪ 音声オン（操作で再生）'):'♪ 音声オフ';$('sound-toggle').setAttribute('aria-pressed',on);}
async function enable(){if($('sound-toggle').disabled)return;$('sound-toggle').disabled=true;try{if(!ctx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error();ctx=new AC();master=ctx.createGain();music=ctx.createGain();effects=ctx.createGain();master.gain.value=0;music.connect(master);effects.connect(master);master.connect(ctx.destination);}await ctx.resume();on=true;next=ctx.currentTime+.1;update();schedule();if(!timer)timer=setInterval(schedule,350);$('sound-status').textContent='オリジナルBGMと操作音';}catch{on=false;$('sound-status').textContent='音声を開始できませんでした。音声ボタンをもう一度押してください。';update();}finally{$('sound-toggle').disabled=false}}
function disable(){on=false;$('sound-status').textContent='音声はオフです。';clearInterval(timer);timer=null;stopVoices();update();if(ctx)ctx.suspend().catch(()=>{});}
$('sound-toggle').onclick=()=>{if(on)disable();else enable()};$('sound-settings').onclick=()=>$('sound-dialog').showModal();$('close-sound').onclick=()=>$('sound-dialog').close();
$('master-volume').oninput=()=>{$('volume-value').textContent=$('master-volume').value+'%';update()};$('music-enabled').onchange=()=>{stopVoices('music');if(ctx)next=ctx.currentTime+.1;update();schedule()};$('effects-enabled').onchange=update;
function effect(kind='tap'){if(!on||!ctx||ctx.state!=='running'||!$('effects-enabled').checked)return;const notes=kind==='delete'?[55,48]:kind==='add'?[60,67,72]:kind==='mode'?[60,64,71]:[76];notes.forEach((n,i)=>note(n,i*.07,kind==='tap'?.16:.42,.09,'effect'));}
document.addEventListener('click',e=>{const b=e.target.closest?.('button');if(!b||b.disabled||b.closest('#sound-dialog')||b.id.startsWith('sound-')||b.type==='submit')return;effect(b.classList.contains('delete-body')?'delete':b.id.startsWith('mode-')?'mode':'tap')});
document.addEventListener('change',e=>{if(e.target.matches('select')&&!e.target.closest('#sound-dialog'))effect()});document.addEventListener('submit',e=>{if(e.target.id==='add-body'&&e.target.checkValidity())effect('add')});
document.addEventListener('visibilitychange',()=>{if(!ctx||!on)return;if(document.hidden){clearInterval(timer);timer=null;stopVoices();ctx.suspend().catch(()=>{});}else{ctx.resume().then(()=>{if(!on||document.hidden)return;next=ctx.currentTime+.1;schedule();if(!timer)timer=setInterval(schedule,350)}).catch(()=>{})}});
function startOnInteraction(e){if(!on||ctx?.state==='running'||e.target.closest?.('#sound-toggle'))return;if(e.type==='keydown'&&(e.repeat||e.ctrlKey||e.metaKey||e.altKey))return;enable();}
document.addEventListener('pointerdown',startOnInteraction);document.addEventListener('keydown',startOnInteraction);document.addEventListener('click',startOnInteraction);update();
window.addEventListener('pagehide',disable);return {effect,disable};
}
